### ISSUE TITLE
'/api/flush' unit test can fail

### ISSUE THREAD

**Issue by axel3rd** [peio42/cerberus#9]
On Travis, the `/api/flush` unit test can fail with:

```
  1) /api/flush
       should remove all but current sessions:
      AssertionError: expected [ Array(2) ] to deeply equal [ [ { pseudo: 'Cl', _id: [Object] } ] ]
      + expected - actual
       [
         [
           {
      -      "lastUsed": {
      -        "$lte": 1546727956801
      -      }
      -    }
      -  ]
      -  [
      -    {
             "_id": {
               "$ne": {
                 "equals": [Function]
                 "id": "ab081dcec450ecb2d90c9148"
      
      at /home/travis/build/peio42/cerberus/test/go.js:351:54
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by axel3rd** [comment]
This bug occurs randomly ...

Logs files :
- [cerberus-log-fail.txt](https://github.com/peio42/cerberus/files/2847311/cerberus-log-fail.txt)
- [cerberus-log-ok.txt](https://github.com/peio42/cerberus/files/2847312/cerberus-log-ok.txt)

Some binaries informations are not displayed at same place ... but no major differences after a first quick look.

**Comment by peio42** [comment]
At the beginning of a request, cerberus will remove old sessions, but only if it didn't already do it last minute.
The check was incorrectly set to 60 ms instead of 60 sec. So if the overall testing was more than 60 ms, a call to "deleteMany" to clean old sessions was going to conflict with the expected "deleteMany" from the /api/flush.
A quick patch to set the correct timeout is coming. But a better handling in sinon arguments should be done anyway.
